
apiVersion: v1
kind: Secret
metadata:
  name: jobagent-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXNxbCthc3luY3BnOi8vYWRtaW46cGFzc3dvcmQ@cG9zdGdyZXM6NTQzMi9qb2JhZ2VudA==
  redis-url: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  secret-key: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
